// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhtwqpllkqsgtuybqywr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodHdxcGxsa3FzZ3R1eWJxeXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjQ5NjUsImV4cCI6MjA1OTIwMDk2NX0.qGuEksGaYq150hCRoCkkg0-uYmOP8TIncTuN-syZ6UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);